---
abstract: 'Creates POD examples from custom L<Mojolicious> templates.'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-InsertExample-FromMojoTemplates
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  File::Find::Rule: '0.33'
  MojoX::CustomTemplateFileParser: '0.07'
  Moose: '2.00'
  Path::Tiny: '0.050'
  namespace::sweep: '0.006'
  perl: v5.14.0
resources:
  bugtracker: https://github.com/Csson/p5-Dist-Zilla-Plugin-InsertExample-FromMojoTemplates/issues
  homepage: https://github.com/Csson/p5-Dist-Zilla-Plugin-InsertExample-FromMojoTemplates
  repository: https://github.com/Csson/p5-Dist-Zilla-Plugin-InsertExample-FromMojoTemplates.git
version: 0.01.01
x_contributors:
  - 'Erik Carlsson <info@code301.com>'
